//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.AjunaSolo.NET.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.AjunaSolo.NET.RestClient.Generated.Interfaces;
   using Substrate.AjunaSolo.NET.RestClient.Generated.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      private BaseSubscriptionClient _subscriptionClient;
      public IAssetsControllerClient AssetsControllerClient;
      public IAuraControllerClient AuraControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public ICasinoJamAffiliatesControllerClient CasinoJamAffiliatesControllerClient;
      public ICasinoJamSageControllerClient CasinoJamSageControllerClient;
      public ICasinoJamSeasonsControllerClient CasinoJamSeasonsControllerClient;
      public ICasinoJamTournamentControllerClient CasinoJamTournamentControllerClient;
      public ICouncilControllerClient CouncilControllerClient;
      public IDemocracyControllerClient DemocracyControllerClient;
      public IGrandpaControllerClient GrandpaControllerClient;
      public IIdentityControllerClient IdentityControllerClient;
      public IMigrationsControllerClient MigrationsControllerClient;
      public IMultisigControllerClient MultisigControllerClient;
      public IPreimageControllerClient PreimageControllerClient;
      public IProxyControllerClient ProxyControllerClient;
      public ISchedulerControllerClient SchedulerControllerClient;
      public ISudoControllerClient SudoControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITechnicalCommitteeControllerClient TechnicalCommitteeControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public ITreasuryControllerClient TreasuryControllerClient;
      public IVestingControllerClient VestingControllerClient;
      public Client(HttpClient httpClient, BaseSubscriptionClient subscriptionClient)
      {
         _httpClient = httpClient;
         _subscriptionClient = subscriptionClient;
         AssetsControllerClient = new AssetsControllerClient(_httpClient, _subscriptionClient);
         AuraControllerClient = new AuraControllerClient(_httpClient, _subscriptionClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient, _subscriptionClient);
         CasinoJamAffiliatesControllerClient = new CasinoJamAffiliatesControllerClient(_httpClient, _subscriptionClient);
         CasinoJamSageControllerClient = new CasinoJamSageControllerClient(_httpClient, _subscriptionClient);
         CasinoJamSeasonsControllerClient = new CasinoJamSeasonsControllerClient(_httpClient, _subscriptionClient);
         CasinoJamTournamentControllerClient = new CasinoJamTournamentControllerClient(_httpClient, _subscriptionClient);
         CouncilControllerClient = new CouncilControllerClient(_httpClient, _subscriptionClient);
         DemocracyControllerClient = new DemocracyControllerClient(_httpClient, _subscriptionClient);
         GrandpaControllerClient = new GrandpaControllerClient(_httpClient, _subscriptionClient);
         IdentityControllerClient = new IdentityControllerClient(_httpClient, _subscriptionClient);
         MigrationsControllerClient = new MigrationsControllerClient(_httpClient, _subscriptionClient);
         MultisigControllerClient = new MultisigControllerClient(_httpClient, _subscriptionClient);
         PreimageControllerClient = new PreimageControllerClient(_httpClient, _subscriptionClient);
         ProxyControllerClient = new ProxyControllerClient(_httpClient, _subscriptionClient);
         SchedulerControllerClient = new SchedulerControllerClient(_httpClient, _subscriptionClient);
         SudoControllerClient = new SudoControllerClient(_httpClient, _subscriptionClient);
         SystemControllerClient = new SystemControllerClient(_httpClient, _subscriptionClient);
         TechnicalCommitteeControllerClient = new TechnicalCommitteeControllerClient(_httpClient, _subscriptionClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient, _subscriptionClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient, _subscriptionClient);
         TreasuryControllerClient = new TreasuryControllerClient(_httpClient, _subscriptionClient);
         VestingControllerClient = new VestingControllerClient(_httpClient, _subscriptionClient);
      }
   }
}
