//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.AjunaSolo.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.AjunaSolo.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.AjunaSolo.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetsControllerMockupClient AssetsControllerClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public ICasinoJamAffiliatesControllerMockupClient CasinoJamAffiliatesControllerClient;
      public ICasinoJamSageControllerMockupClient CasinoJamSageControllerClient;
      public ICasinoJamSeasonsControllerMockupClient CasinoJamSeasonsControllerClient;
      public ICasinoJamTournamentControllerMockupClient CasinoJamTournamentControllerClient;
      public ICouncilControllerMockupClient CouncilControllerClient;
      public IDemocracyControllerMockupClient DemocracyControllerClient;
      public IGrandpaControllerMockupClient GrandpaControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public IMigrationsControllerMockupClient MigrationsControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITechnicalCommitteeControllerMockupClient TechnicalCommitteeControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetsControllerClient = new AssetsControllerMockupClient(_httpClient);
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         CasinoJamAffiliatesControllerClient = new CasinoJamAffiliatesControllerMockupClient(_httpClient);
         CasinoJamSageControllerClient = new CasinoJamSageControllerMockupClient(_httpClient);
         CasinoJamSeasonsControllerClient = new CasinoJamSeasonsControllerMockupClient(_httpClient);
         CasinoJamTournamentControllerClient = new CasinoJamTournamentControllerMockupClient(_httpClient);
         CouncilControllerClient = new CouncilControllerMockupClient(_httpClient);
         DemocracyControllerClient = new DemocracyControllerMockupClient(_httpClient);
         GrandpaControllerClient = new GrandpaControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         MigrationsControllerClient = new MigrationsControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TechnicalCommitteeControllerClient = new TechnicalCommitteeControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
      }
   }
}
